name: chronicle

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - pip
  - sqlite

  # Core utilities
  - psutil
  - fastapi
  - uvicorn
  # Pip installs
  - pip:
      - pywin32